### ISSUE TITLE
Track covariance to be changed

### ISSUE THREAD

**Issue by clementhelsens** [key4hep/k4SimDelphes#10]
Delphes returns the full covariance:

https://github.com/delphes/delphes/blob/master/modules/TrackCovariance.cc#L122

but in edm4hep we use the diagonal terms also stored in delphes:
https://github.com/key4hep/k4SimDelphes/blob/bf31367b3d6b62b8b1b4252469ff8235499ab038/converter/src/DelphesEDM4HepConverter.cc#L445-L449

We need to change that to store the full covariance matrix including correlations. Need to pay attention to the units

**Comment by tmadlener** [comment]
Here we also have to pay attention that the full covariance is only available from more recent delphes versions.

**Comment by vvolkl** [comment]
Yes indeed, In fact only the latest `3.4.3pre06` tag can be used for this, the previous ones have unit bugs. @clementhelsens I think we can just port the fccsw code for this, that has been tested, right? https://github.com/HEP-FCC/FCCSW/blob/master/Sim/SimDelphesInterface/src/DelphesSaveChargedParticles.cpp

**Comment by clementhelsens** [comment]
@vvolkl , yes the FCC implementation has been tested. The only difference is that the track basis is different in FCCSW (ACTS like)

**Comment by andresailer** [comment]
Also note: https://github.com/key4hep/EDM4hep/pull/108

**Comment by tmadlener** [comment]
Is this still open or has this been fixed (see #27) and can be closed? In any case related: #46

**Comment by clementhelsens** [comment]
yes, this can be closed
