### ISSUE TITLE
Naming convention in includes, namespaces

### ISSUE THREAD

**Issue by vvolkl** [key4hep/k4SimDelphes#11]
Currently uses `k4simdelphes` in lowercase, while the convention should be to stay consistent with the projectname,  including capitalization.

**Comment by tmadlener** [comment]
I think this has all been fixed by now.

`git grep k4simdelphes` and `find . -type f name "*k4simdelphes*"` return only matches that are either lowercase names of Gaudi options file in the examples or a few in docstrings.

Can be reopened when we still discover violations later.
