### ISSUE TITLE
DelphesROOT_EDM4HEP failes

### ISSUE THREAD

**Issue by chekanov** [key4hep/k4SimDelphes#123]
Hello,

 I was testing DelphesROOT_EDM4HEP, but it looks like I cannot read truth level information created by Delphes 3.5 using this binary file. I use:

`/cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh`

on el9. First I was using Delphes 3.5 with the supplied cards/gen_card.tcl which fills truth-level "particle" record.

This gives me "truth.root" 

Then I checked 

`DelphesROOT delphes_card_IDEA.tcl test_RECO.root truth.root `

It works fine. Then I ran:

` DelphesROOT_EDM4HEP card_IDEA.tcl edm4hep.tcl test_EDM.root truth.root `

It suck on 1st events (without error)

best, Sergei

**Comment by chekanov** [comment]
Hi, Thomas

 Please try this file: https://mc.hep.anl.gov/asc/hepsim/tmp/gev91ee_zboson_001.root 

It was made with Delphes 3.5 using the card cards/gen_card.tcl. It works with the original Delphes, but fails with DelphesROOT_EDM4HEP

best

**Comment by chekanov** [comment]
Sorry, I've forgotten. My edm4hep.tcl for this example looks like this:
```

 module EDM4HepOutput EDM4HepOutput {
    add ReconstructedParticleCollections EFlowTrack EFlowPhoton EFlowNeutralHadron
    add GenParticleCollections           Particle
    add JetCollections                   Jet
    add MuonCollections                  Muon
    add ElectronCollections              Electron
    add PhotonCollections                Photon
    set RecoParticleCollectionName       ReconstructedParticles
    set MCRecoAssociationCollectionName  MCRecoAssociations
}
```

**Comment by chekanov** [comment]
Hi, Thomas

Thanks, exactly, it never starts the loop over events. Should I just use

` source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh`

for checking?

best, Sergei

**Comment by tmadlener** [comment]
Hi Sergei, the changes should be available from the nightlies tomorrow. (The setup script you use is the correct one)

**Comment by chekanov** [comment]
Hi, Thomas

 Thanks. It looks like it works now. At least it loops over events. I'll check  the outputs.

 best, Sergei
