### ISSUE TITLE
DelphesRootReader_ee_91gev test failing

### ISSUE THREAD

**Issue by andresailer** [key4hep/k4SimDelphes#129]
2/7 Test #5: DelphesRootReader_ee_91gev .....................***Failed    8.78 sec

See log files.

**Comment by tmadlener** [comment]
The test seems to be pretty flaky. I get a roughly 30% failure rate locally. The main issue is that it's not entirely easy to reproduce, because even with a fixed random seed for delphes I sometimes get it to pass sometimes and to fail the other times.

**Comment by andresailer** [comment]
We can add a `--repeat until-pass:5` to ctest then

**Comment by tmadlener** [comment]
I didn't even know that is a thing... Let me check quickly whether I find an obvious issue with the seeding just to rule out any stupid issues.

**Comment by andresailer** [comment]
Although of course it depends on why that test actually fails? Just flaky comparison.

**Comment by andresailer** [comment]
That missing ctest hook is  probably something @jmcarcell can fix.

**Comment by tmadlener** [comment]
It seems to be very consistent in CI, even `--repeat until-pass:5` doesn't do much there: https://github.com/key4hep/k4SimDelphes/actions/runs/11147612771/job/30982426010?pr=130
