### ISSUE TITLE
Change the default output name for the reco - mc links

### ISSUE THREAD

**Issue by tmadlener** [key4hep/k4SimDelphes#139]
Currently the default output name in the example for the link between Reco and MC particles is slightly misleading regarding the direction of the link. Following the EDM4hep naming convention the name suggests that MC is `from` and reco is `to`, when in fact the `RecoMCParticleLink` defines them in the opposite way.

https://github.com/key4hep/k4SimDelphes/blob/c79aaf7576186d98fabd2928ad5b40036f30c909/examples/edm4hep_output_config.tcl#L12

- [x] We have to make sure that changing the example here doesn't break any production

@BrieucF just FYI

**Comment by tmadlener** [comment]
@kjvbrt also as a heads up, following this change for FCC would break FCCAnalyses quite heavily, I think.

**Comment by BrieucF** [comment]
Thanks @tmadlener for opening the issue and @bistapf for checking already the impact it would have. 

I also checked whether there were other definitions of `EDM4HepOutput` in [FCC-Config](https://github.com/HEP-FCC/FCC-config) (there is none). In EventProducer, there is nevertheless the possibility to use a custom `EDM4HepOutput` tcl file: [EventProducer](https://github.com/HEP-FCC/EventProducer/blob/master/bin/run.py#L57). 

I will investigate further and let you know

**Comment by BrieucF** [comment]
Edit to the above: there is one in FCC-config (https://github.com/HEP-FCC/FCC-config/blob/winter2023/FCCee/Delphes/edm4hep_IDEA.tcl) but it is in the winter2023 branch which is used with a fixed stable release using the 'old' associations. Everything is fine in this regard.

So the last word goes to you @bistapf !

**Comment by kjvbrt** [comment]
Hi, the change will affect mostly user code (analysis scripts) not really any production code and it does not matter if users use FCCAnalyses with datasource or not.
As long as the name is consistent among the samples in the campaign, this should be fine.

**Comment by bistapf** [comment]
Hi @BrieucF, all. Thanks a lot for the follow-up. Given that for FCC-hh I actually do use a custom edm4hep output config file already, I think there isn't any technial issue from my side. For the record, we agreed for now to keep the old name in the FCC-hh v06 production, and once we move to a new production we will update the name also. 

TL,DR: Yes, please go ahead and merge.

**Comment by jmcarcell** [comment]
What about this line? https://github.com/key4hep/k4SimDelphes/blob/a3c5b0efdaa071201b863e4bfc3411934107e37c/framework/k4SimDelphes/examples/options/edm4hep_output_config.tcl#L11
Should it also be changed? There is already a deprecation warning for this name from a few months ago: https://github.com/key4hep/k4SimDelphes/blob/main/converter/include/k4SimDelphes/DelphesEDM4HepOutputConfiguration.h#L156

**Comment by tmadlener** [comment]
Ah, damnit. Good catch. Didn't even think about that. That should definitely also be fixed. PR in the making.

**Comment by jmcarcell** [comment]
What about the warning, should we turn it into an error or keep it there for cards that still use the old name?

**Comment by tmadlener** [comment]
I would keep it as a warning for now and make it an error after the next tag only.
