### ISSUE TITLE
k4SimDelphes stuck in a loop

### ISSUE THREAD

**Issue by clementhelsens** [key4hep/k4SimDelphes#32]
I have noticed, running the EvtGen+Pythia8 executable, that at some point, the code will get stuck in an infinite loop.
I have not been able to see this with Pythia8 only but can not exclude it happens there as well.
When someone has time, it'd be interesting to understand where it occurs.

**Comment by tmadlener** [comment]
This seems to be happening in `PythiaEvtGen_Interface::decay`, specifically in this loop:
https://github.com/key4hep/k4SimDelphes/blob/804ffbad655d5bad16c4c9ef2a044c1f728d60bd/standalone/src/PythiaEvtGen_Interface.cc#L222-L240

Additionally, it seems to only happen if `regenerate == false`. At least I can get past an event that enters an infinite loop if I set it to `true`.

I am not entirely sure what is going on an a "physics" level in this case, but it seems that pythia is not able to hadronize in such a way that the desired signal appears for certain events and thus it gets stuck if we do not regenerate the whole event from scratch(?).

**Comment by tmadlener** [comment]
Fixed by #50
